=== mzearing/AgentNodes/backend/agent_nodes.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Complex",
  "type": "object",
  "properties": {
    "inputs": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/DataType"
      }
    },
    "outputs": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/DataType"
      }
    },
    "end_node": {
      "type": "string",
      "format": "uuid"
    },
    "defaults": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/DataValue"
      }
    },
    "instances": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/Instance"
      }
    }
  },
  "required": [
    "inputs",
    "outputs",
    "end_node",
    "defaults",
    "instances"
  ],
  "$defs": {
    "DataType": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "Array",
            "String",
            "Integer",
            "Float",
            "Boolean",
            "Byte",
            "Handle",
            "Object",
            "None"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Agent": {
              "$ref": "#/$defs/AgentType"
            }
          },
          "required": [
            "Agent"
          ],
          "additionalProperties": false
        }
      ]
    },
    "AgentType": {
      "type": "string",
      "enum": [
        "OpenAi",
        "OpenRouter"
      ]
    },
    "DataValue": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "integer",
          "format": "int64"
        },
        {
          "type": "number",
          "format": "double"
        },
        {
          "type": "boolean"
        },
        {
          "type": "integer",
          "format": "uint8",
          "minimum": 0,
          "maximum": 255
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/DataValue"
          }
        },
        {
          "type": "string",
          "format": "uuid"
        },
        {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/DataValue"
          }
        },
        {
          "type": "array",
          "prefixItems": [
            {
              "$ref": "#/$defs/AgentType"
            },
            {
              "type": "string",
              "format": "uuid"
            }
          ],
          "minItems": 2,
          "maxItems": 2
        },
        {
          "type": "null"
        }
      ]
    },
    "Instance": {
      "type": "object",
      "properties": {
        "node_type": {
          "$ref": "#/$defs/NodeType"
        },
        "default_overrides": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/DataValue"
          }
        },
        "outputs": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uuid"
          }
        },
        "control_flow_in": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "array",
              "prefixItems": [
                {
                  "type": "string",
                  "format": "uuid"
                },
                {
                  "type": "integer",
                  "format": "uint",
                  "minimum": 0
                }
              ],
              "minItems": 2,
              "maxItems": 2
            }
          }
        },
        "control_flow_out": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "array",
              "prefixItems": [
                {
                  "type": "string",
                  "format": "uuid"
                },
                {
                  "type": "integer",
                  "format": "uint",
                  "minimum": 0
                }
              ],
              "minItems": 2,
              "maxItems": 2
            }
          }
        },
        "inputs": {
          "type": "array",
          "items": {
            "type": "array",
            "prefixItems": [
              {
                "$ref": "#/$defs/DataType"
              },
              {
                "type": "string",
                "format": "uuid"
              },
              {
                "type": "integer",
                "format": "uint",
                "minimum": 0
              }
            ],
            "minItems": 3,
            "maxItems": 3
          }
        }
      },
      "required": [
        "node_type",
        "default_overrides",
        "outputs",
        "control_flow_in",
        "control_flow_out",
        "inputs"
      ]
    },
    "NodeType": {
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "Atomic": {
              "$ref": "#/$defs/AtomicType"
            }
          },
          "required": [
            "Atomic"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "Complex": {
              "type": "string"
            }
          },
          "required": [
            "Complex"
          ],
          "additionalProperties": false
        }
      ]
    },
    "AtomicType": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "Print",
            "Replace",
            "IsNone"
          ]
        },
        {
          "type": "object",
          "properties": {
            "BinOp": {
              "$ref": "#/$defs/AtomicBinOp"
            }
          },
          "required": [
            "BinOp"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "UnaryOp": {
              "$ref": "#/$defs/AtomicUnaryOp"
            }
          },
          "required": [
            "UnaryOp"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "Value": {
              "$ref": "#/$defs/DataValue"
            }
          },
          "required": [
            "Value"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "Control": {
              "$ref": "#/$defs/ControlFlow"
            }
          },
          "required": [
            "Control"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "Variable": {
              "type": "array",
              "prefixItems": [
                {
                  "$ref": "#/$defs/Variable"
                },
                {
                  "type": "string"
                }
              ],
              "minItems": 2,
              "maxItems": 2
            }
          },
          "required": [
            "Variable"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "Io": {
              "$ref": "#/$defs/AtomicIo"
            }
          },
          "required": [
            "Io"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "Cast": {
              "$ref": "#/$defs/DataType"
            }
          },
          "required": [
            "Cast"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "LogicalOp": {
              "$ref": "#/$defs/AtomicLogic"
            }
          },
          "required": [
            "LogicalOp"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "AgentOp": {
              "$ref": "#/$defs/AgentOperation"
            }
          },
          "required": [
            "AgentOp"
          ],
          "additionalProperties": false
        }
      ]
    },
    "AtomicBinOp": {
      "type": "string",
      "enum": [
        "Add",
        "Sub",
        "Mul",
        "Div",
        "Pow",
        "Mod"
      ]
    },
    "AtomicUnaryOp": {
      "type": "string",
      "enum": [
        "Neg"
      ]
    },
    "ControlFlow": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "Start",
            "End",
            "If"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Loop": {
              "$ref": "#/$defs/LoopNodes"
            }
          },
          "required": [
            "Loop"
          ],
          "additionalProperties": false
        }
      ]
    },
    "LoopNodes": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "Start"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Continue": {
              "type": "string",
              "format": "uuid"
            }
          },
          "required": [
            "Continue"
          ],
          "additionalProperties": false
        }
      ]
    },
    "Variable": {
      "type": "string",
      "enum": [
        "Set",
        "Get"
      ]
    },
    "AtomicIo": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "ConsoleInput",
            "Read",
            "Write",
            "GetLine"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Open": {
              "$ref": "#/$defs/IoType"
            }
          },
          "required": [
            "Open"
          ],
          "additionalProperties": false
        }
      ]
    },
    "IoType": {
      "type": "string",
      "enum": [
        "File",
        "TcpSocket"
      ]
    },
    "AtomicLogic": {
      "type": "string",
      "enum": [
        "And",
        "Or",
        "Xor",
        "Not",
        "Eq"
      ]
    },
    "AgentOperation": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "Send",
            "Recieve"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Create": {
              "$ref": "#/$defs/AgentType"
            }
          },
          "required": [
            "Create"
          ],
          "additionalProperties": false
        }
      ]
    }
  }
}

=== mzearing/AgentNodes/agentnodes-editor/node-definitions/complex/group-test-programs/ask-llm/compiled.json
{
  "inputs": [],
  "outputs": [
    "String"
  ],
  "defaults": {},
  "instances": {
    "02fe49fa-8d5e-47ac-abc0-8da936835af9": {
      "node_type": {
        "Atomic": {
          "Control": "Start"
        }
      },
      "default_overrides": {},
      "outputs": [],
      "control_flow_in": [],
      "control_flow_out": [
        [
          [
            "f26a2237-df7a-484a-b814-f2d8af7566fe",
            0
          ]
        ]
      ],
      "inputs": []
    },
    "9b87163b-8b13-49e2-a2d5-331dfe17c784": {
      "node_type": {
        "Atomic": {
          "Value": "gpt-4o"
        }
      },
      "default_overrides": {},
      "outputs": [
        "30911659-0dc5-4ee7-b586-b08a0909c089"
      ],
      "control_flow_in": [
        [
          [
            "f26a2237-df7a-484a-b814-f2d8af7566fe",
            0
          ]
        ]
      ],
      "control_flow_out": [
        []
      ],
      "inputs": []
    },
    "851dc390-255d-440d-b223-4d579aa22729": {
      "node_type": {
        "Atomic": {
          "Value": 0.7
        }
      },
      "default_overrides": {},
      "outputs": [
        "30911659-0dc5-4ee7-b586-b08a0909c089"
      ],
      "control_flow_in": [
        [
          [
            "f26a2237-df7a-484a-b814-f2d8af7566fe",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "3d7dfcca-48c9-4022-903e-075448ac1e6a",
            0
          ]
        ]
      ],
      "inputs": []
    },
    "30911659-0dc5-4ee7-b586-b08a0909c089": {
      "node_type": {
        "Atomic": {
          "AgentOp": {
            "Create": "OpenAi"
          }
        }
      },
      "default_overrides": {},
      "outputs": [
        "0ac4b09a-498c-4d4e-88d9-b59bfcff2ae8",
        "80eb128a-c163-4773-80e3-ff5505173319"
      ],
      "control_flow_in": [
        [
          [
            "3d7dfcca-48c9-4022-903e-075448ac1e6a",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "0ac4b09a-498c-4d4e-88d9-b59bfcff2ae8",
            0
          ]
        ]
      ],
      "inputs": [
        [
          "String",
          "9b87163b-8b13-49e2-a2d5-331dfe17c784",
          0
        ],
        [
          "None",
          "3d7dfcca-48c9-4022-903e-075448ac1e6a",
          0
        ],
        [
          "Float",
          "851dc390-255d-440d-b223-4d579aa22729",
          0
        ]
      ]
    },
    "0ac4b09a-498c-4d4e-88d9-b59bfcff2ae8": {
      "node_type": {
        "Atomic": {
          "AgentOp": "Send"
        }
      },
      "default_overrides": {},
      "outputs": [],
      "control_flow_in": [
        [
          [
            "30911659-0dc5-4ee7-b586-b08a0909c089",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "80eb128a-c163-4773-80e3-ff5505173319",
            0
          ]
        ]
      ],
      "inputs": [
        [
          {
            "Agent": "OpenAi"
          },
          "30911659-0dc5-4ee7-b586-b08a0909c089",
          0
        ],
        [
          "String",
          "f26a2237-df7a-484a-b814-f2d8af7566fe",
          0
        ]
      ]
    },
    "80eb128a-c163-4773-80e3-ff5505173319": {
      "node_type": {
        "Atomic": {
          "AgentOp": "Recieve"
        }
      },
      "default_overrides": {},
      "outputs": [
        "b2be1b1d-937e-4dc7-bdc6-d91089666772",
        "fb2389ec-ca17-4b32-90ca-3a7725096da1"
      ],
      "control_flow_in": [
        [
          [
            "0ac4b09a-498c-4d4e-88d9-b59bfcff2ae8",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "b2be1b1d-937e-4dc7-bdc6-d91089666772",
            0
          ]
        ]
      ],
      "inputs": [
        [
          {
            "Agent": "OpenAi"
          },
          "30911659-0dc5-4ee7-b586-b08a0909c089",
          0
        ]
      ]
    },
    "b2be1b1d-937e-4dc7-bdc6-d91089666772": {
      "node_type": {
        "Atomic": "Print"
      },
      "default_overrides": {},
      "outputs": [],
      "control_flow_in": [
        [
          [
            "80eb128a-c163-4773-80e3-ff5505173319",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "fb2389ec-ca17-4b32-90ca-3a7725096da1",
            0
          ]
        ]
      ],
      "inputs": [
        [
          "String",
          "80eb128a-c163-4773-80e3-ff5505173319",
          0
        ]
      ]
    },
    "fb2389ec-ca17-4b32-90ca-3a7725096da1": {
      "node_type": {
        "Atomic": {
          "Control": "End"
        }
      },
      "default_overrides": {},
      "outputs": [
        "f14937c5-ec15-431a-96dc-38dd1a550d1e"
      ],
      "control_flow_in": [
        [
          [
            "b2be1b1d-937e-4dc7-bdc6-d91089666772",
            0
          ]
        ]
      ],
      "control_flow_out": [],
      "inputs": [
        [
          "String",
          "80eb128a-c163-4773-80e3-ff5505173319",
          0
        ]
      ]
    },
    "3d7dfcca-48c9-4022-903e-075448ac1e6a": {
      "node_type": {
        "Atomic": {
          "Value": null
        }
      },
      "default_overrides": {},
      "outputs": [
        "30911659-0dc5-4ee7-b586-b08a0909c089"
      ],
      "control_flow_in": [
        [
          [
            "851dc390-255d-440d-b223-4d579aa22729",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "30911659-0dc5-4ee7-b586-b08a0909c089",
            0
          ]
        ]
      ],
      "inputs": []
    },
    "f26a2237-df7a-484a-b814-f2d8af7566fe": {
      "node_type": {
        "Atomic": {
          "Value": "Hello"
        }
      },
      "default_overrides": {},
      "outputs": [
        "0ac4b09a-498c-4d4e-88d9-b59bfcff2ae8"
      ],
      "control_flow_in": [
        [
          [
            "02fe49fa-8d5e-47ac-abc0-8da936835af9",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "9b87163b-8b13-49e2-a2d5-331dfe17c784",
            0
          ],
          [
            "851dc390-255d-440d-b223-4d579aa22729",
            0
          ]
        ]
      ],
      "inputs": []
    }
  },
  "end_node": "fb2389ec-ca17-4b32-90ca-3a7725096da1"
}

=== mzearing/AgentNodes/agentnodes-editor/node-definitions/complex/group-test-programs/add-two-numbers/compiled.json
{
  "inputs": [
    "Integer",
    "Integer"
  ],
  "outputs": [
    "Integer"
  ],
  "defaults": {},
  "instances": {
    "18534836-e71a-47a2-9c38-1e094bdf26d0": {
      "node_type": {
        "Atomic": {
          "Control": "Start"
        }
      },
      "default_overrides": {},
      "outputs": [
        "aad9b842-fe0c-42a5-8d64-85e7354a54be",
        "aad9b842-fe0c-42a5-8d64-85e7354a54be"
      ],
      "control_flow_in": [],
      "control_flow_out": [
        [
          [
            "aad9b842-fe0c-42a5-8d64-85e7354a54be",
            0
          ]
        ]
      ],
      "inputs": []
    },
    "aad9b842-fe0c-42a5-8d64-85e7354a54be": {
      "node_type": {
        "Atomic": {
          "BinOp": "Add"
        }
      },
      "default_overrides": {},
      "outputs": [
        "5e52c820-9542-4807-902f-ea31822b33fe"
      ],
      "control_flow_in": [
        [
          [
            "18534836-e71a-47a2-9c38-1e094bdf26d0",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "5e52c820-9542-4807-902f-ea31822b33fe",
            0
          ]
        ]
      ],
      "inputs": [
        [
          "Integer",
          "18534836-e71a-47a2-9c38-1e094bdf26d0",
          0
        ],
        [
          "Integer",
          "18534836-e71a-47a2-9c38-1e094bdf26d0",
          1
        ]
      ]
    },
    "5e52c820-9542-4807-902f-ea31822b33fe": {
      "node_type": {
        "Atomic": {
          "Control": "End"
        }
      },
      "default_overrides": {},
      "outputs": [
        "8cde10a5-262f-495b-9103-70c567891520"
      ],
      "control_flow_in": [
        [
          [
            "aad9b842-fe0c-42a5-8d64-85e7354a54be",
            0
          ]
        ]
      ],
      "control_flow_out": [],
      "inputs": [
        [
          "Integer",
          "aad9b842-fe0c-42a5-8d64-85e7354a54be",
          0
        ]
      ]
    }
  },
  "end_node": "5e52c820-9542-4807-902f-ea31822b33fe"
}

=== mzearing/AgentNodes/backend/testprogs/while_test.json
{
  "defaults": {},
  "inputs": [],
  "end_node": "0bee5a7c-2d5f-11f1-834f-00155d65b92e",
  "outputs": [],
  "instances": {
    "eb5a58f4-2d56-11f1-aed2-00155d65b92e":{
      "control_flow_in": [],
      "control_flow_out": [[["e5d0cc8c-2d57-11f1-a4b9-00155d65b92e", 0]]],
      "inputs": [],
      "outputs": [],
      "default_overrides": {},
      "node_type":{
        "Atomic":{
          "Control":"Start"
        }
      }
    },
    "e5d0cc8c-2d57-11f1-a4b9-00155d65b92e":{
      "control_flow_in": [[["eb5a58f4-2d56-11f1-aed2-00155d65b92e",0]]],
      "control_flow_out": [[["19b1d0d6-2d59-11f1-b95f-00155d65b92e", 0]]],
      "inputs": [],
      "outputs": ["19b1d0d6-2d59-11f1-b95f-00155d65b92e"],
      "default_overrides": {},
      "node_type":
      {
        "Atomic":{
          "Value":0
        }
      }
    },
    "19b1d0d6-2d59-11f1-b95f-00155d65b92e":{
      "control_flow_in": [[["e5d0cc8c-2d57-11f1-a4b9-00155d65b92e", 0]]],
      "control_flow_out": [[["15368b12-2d5b-11f1-a413-00155d65b92e", 0]]],
      "inputs": [["Integer", "e5d0cc8c-2d57-11f1-a4b9-00155d65b92e", 0]],
      "outputs": [],
      "default_overrides": {},
      "node_type":{
        "Atomic":{"Variable": ["Set", "Counter"]}
      }
    },
    "15368b12-2d5b-11f1-a413-00155d65b92e":{
      "control_flow_in": [[["19b1d0d6-2d59-11f1-b95f-00155d65b92e", 0]]],
      "control_flow_out": [[["46925fd2-2d5c-11f1-b293-00155d65b92e", 0]]],
      "inputs": [],
      "outputs": [],
      "default_overrides": {},
      "node_type":{
        "Atomic":{
          "Control":{"Loop":"Start"}
        }
      }
    },
    "46925fd2-2d5c-11f1-b293-00155d65b92e":{
      "control_flow_in": [[["15368b12-2d5b-11f1-a413-00155d65b92e", 0]]],
      "control_flow_out": [[["dd8cdf52-2d5c-11f1-8047-00155d65b92e", 0], ["75f24fc8-2d5f-11f1-b159-00155d65b92e", 0]]],
      "inputs": [],
      "outputs": ["dd8cdf52-2d5c-11f1-8047-00155d65b92e", "8d281f26-2d5d-11f1-b546-00155d65b92e", "e7671922-2d5f-11f1-b4bb-00155d65b92e"],
      "default_overrides": {},
      "node_type":{
        "Atomic":{"Variable": ["Get", "Counter"]}
      }
    },
    "dd8cdf52-2d5c-11f1-8047-00155d65b92e":{
      "control_flow_in": [[["46925fd2-2d5c-11f1-b293-00155d65b92e", 0]]],
      "control_flow_out": [[["0bbfe3ce-2d5d-11f1-b89b-00155d65b92e", 0]]],
      "inputs": [["Integer", "46925fd2-2d5c-11f1-b293-00155d65b92e", 0]],
      "outputs": [],
      "default_overrides": {},
      "node_type":{
        "Atomic":"Print"
      }
    },
    "0bbfe3ce-2d5d-11f1-b89b-00155d65b92e":{
      "control_flow_in": [[["dd8cdf52-2d5c-11f1-8047-00155d65b92e", 0]]],
      "control_flow_out": [[["8d281f26-2d5d-11f1-b546-00155d65b92e", 0]]],
      "inputs": [],
      "outputs": ["8d281f26-2d5d-11f1-b546-00155d65b92e"],
      "default_overrides": {},
      "node_type":{
        "Atomic":{"Value":10}
      }
    },
    "8d281f26-2d5d-11f1-b546-00155d65b92e":{
      "control_flow_in": [[["0bbfe3ce-2d5d-11f1-b89b-00155d65b92e", 0]]],
      "control_flow_out": [[["035677a6-2d5e-11f1-a539-00155d65b92e", 0]]],
      "inputs": [
        ["Integer", "0bbfe3ce-2d5d-11f1-b89b-00155d65b92e", 0], 
        ["Integer", "46925fd2-2d5c-11f1-b293-00155d65b92e", 0]
      ],
      "outputs": ["035677a6-2d5e-11f1-a539-00155d65b92e"],
      "default_overrides": {},
      "node_type":{
        "Atomic":{"LogicalOp": "Eq"}
      }
    },
    "035677a6-2d5e-11f1-a539-00155d65b92e":
    {
      "control_flow_in": [[["8d281f26-2d5d-11f1-b546-00155d65b92e", 0]]],
      "control_flow_out": [[["85194b56-2d5e-11f1-bfb4-00155d65b92e", 0]], [["0bee5a7c-2d5f-11f1-834f-00155d65b92e", 1]]],
      "inputs": [["Boolean", "8d281f26-2d5d-11f1-b546-00155d65b92e", 0]],
      "outputs": [],
      "default_overrides": {},
      "node_type":{
        "Atomic":{"Control":"If"}
      }
    },
    "85194b56-2d5e-11f1-bfb4-00155d65b92e":{
      "control_flow_in": [[["035677a6-2d5e-11f1-a539-00155d65b92e", 0]]],
      "control_flow_out": [],
      "inputs": [],
      "outputs": [],
      "default_overrides": {},
      "node_type":{
        "Atomic":{
          "Control":
          {
            "Loop":
            {
              "Continue": "15368b12-2d5b-11f1-a413-00155d65b92e"
            }
          }
        }
      }
    },
    "0bee5a7c-2d5f-11f1-834f-00155d65b92e":{
      "control_flow_in": [[["035677a6-2d5e-11f1-a539-00155d65b92e", 1]]],
      "control_flow_out": [],
      "inputs": [],
      "outputs": [],
      "default_overrides": {},
      "node_type":{
        "Atomic":{
          "Control":"End"
        }
      }
    },
    "75f24fc8-2d5f-11f1-b159-00155d65b92e":{
      "control_flow_in": [[["46925fd2-2d5c-11f1-b293-00155d65b92e", 0]]],
      "control_flow_out": [],
      "inputs": [],
      "outputs": ["e7671922-2d5f-11f1-b4bb-00155d65b92e"],
      "default_overrides": {},
      "node_type":{
        "Atomic":{"Value":1}
      }
    },
    "e7671922-2d5f-11f1-b4bb-00155d65b92e":{
      "control_flow_in": [[["75f24fc8-2d5f-11f1-b159-00155d65b92e", 0]]],
      "control_flow_out": [],
      "inputs": [["Integer", "46925fd2-2d5c-11f1-b293-00155d65b92e", 0], ["Integer", "75f24fc8-2d5f-11f1-b159-00155d65b92e", 0]],
      "outputs": [],
      "default_overrides": {},
      "node_type":{
        "Atomic":{"BinOp": "Add"}
      }
    },
    "4a2a0330-2d60-11f1-98c6-00155d65b92e":
    {
      "control_flow_in": [[["e7671922-2d5f-11f1-b4bb-00155d65b92e", 0]]],
      "control_flow_out": [],
      "inputs": [["Integer", "e7671922-2d5f-11f1-b4bb-00155d65b92e", 0]],
      "outputs": [],
      "default_overrides": {},
      "node_type":{
        "Atomic":{
          "Variable": ["Set", "Counter"]
        }
      }
    }
  }
}
