=== mzearing/AgentNodes/backend/agent_nodes.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Complex",
  "type": "object",
  "properties": {
    "inputs": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/DataType"
      }
    },
    "outputs": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/DataType"
      }
    },
    "end_node": {
      "type": "string",
      "format": "uuid"
    },
    "defaults": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/DataValue"
      }
    },
    "instances": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/$defs/Instance"
      }
    }
  },
  "required": [
    "inputs",
    "outputs",
    "end_node",
    "defaults",
    "instances"
  ],
  "$defs": {
    "DataType": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "Array",
            "String",
            "Integer",
            "Float",
            "Boolean",
            "Byte",
            "Handle",
            "Object",
            "None"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Agent": {
              "$ref": "#/$defs/AgentType"
            }
          },
          "required": [
            "Agent"
          ],
          "additionalProperties": false
        }
      ]
    },
    "AgentType": {
      "type": "string",
      "enum": [
        "OpenAi",
        "OpenRouter"
      ]
    },
    "DataValue": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "integer",
          "format": "int64"
        },
        {
          "type": "number",
          "format": "double"
        },
        {
          "type": "boolean"
        },
        {
          "type": "integer",
          "format": "uint8",
          "minimum": 0,
          "maximum": 255
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/$defs/DataValue"
          }
        },
        {
          "type": "string",
          "format": "uuid"
        },
        {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/DataValue"
          }
        },
        {
          "type": "array",
          "prefixItems": [
            {
              "$ref": "#/$defs/AgentType"
            },
            {
              "type": "string",
              "format": "uuid"
            }
          ],
          "minItems": 2,
          "maxItems": 2
        },
        {
          "type": "null"
        }
      ]
    },
    "Instance": {
      "type": "object",
      "properties": {
        "node_type": {
          "$ref": "#/$defs/NodeType"
        },
        "default_overrides": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/DataValue"
          }
        },
        "outputs": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uuid"
          }
        },
        "control_flow_in": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "array",
              "prefixItems": [
                {
                  "type": "string",
                  "format": "uuid"
                },
                {
                  "type": "integer",
                  "format": "uint",
                  "minimum": 0
                }
              ],
              "minItems": 2,
              "maxItems": 2
            }
          }
        },
        "control_flow_out": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "array",
              "prefixItems": [
                {
                  "type": "string",
                  "format": "uuid"
                },
                {
                  "type": "integer",
                  "format": "uint",
                  "minimum": 0
                }
              ],
              "minItems": 2,
              "maxItems": 2
            }
          }
        },
        "inputs": {
          "type": "array",
          "items": {
            "type": "array",
            "prefixItems": [
              {
                "$ref": "#/$defs/DataType"
              },
              {
                "type": "string",
                "format": "uuid"
              },
              {
                "type": "integer",
                "format": "uint",
                "minimum": 0
              }
            ],
            "minItems": 3,
            "maxItems": 3
          }
        }
      },
      "required": [
        "node_type",
        "default_overrides",
        "outputs",
        "control_flow_in",
        "control_flow_out",
        "inputs"
      ]
    },
    "NodeType": {
      "oneOf": [
        {
          "type": "object",
          "properties": {
            "Atomic": {
              "$ref": "#/$defs/AtomicType"
            }
          },
          "required": [
            "Atomic"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "Complex": {
              "type": "string"
            }
          },
          "required": [
            "Complex"
          ],
          "additionalProperties": false
        }
      ]
    },
    "AtomicType": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "Print",
            "Replace",
            "IsNone"
          ]
        },
        {
          "type": "object",
          "properties": {
            "BinOp": {
              "$ref": "#/$defs/AtomicBinOp"
            }
          },
          "required": [
            "BinOp"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "UnaryOp": {
              "$ref": "#/$defs/AtomicUnaryOp"
            }
          },
          "required": [
            "UnaryOp"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "Value": {
              "$ref": "#/$defs/DataValue"
            }
          },
          "required": [
            "Value"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "Control": {
              "$ref": "#/$defs/ControlFlow"
            }
          },
          "required": [
            "Control"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "Variable": {
              "type": "array",
              "prefixItems": [
                {
                  "$ref": "#/$defs/Variable"
                },
                {
                  "type": "string"
                }
              ],
              "minItems": 2,
              "maxItems": 2
            }
          },
          "required": [
            "Variable"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "Io": {
              "$ref": "#/$defs/AtomicIo"
            }
          },
          "required": [
            "Io"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "Cast": {
              "$ref": "#/$defs/DataType"
            }
          },
          "required": [
            "Cast"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "LogicalOp": {
              "$ref": "#/$defs/AtomicLogic"
            }
          },
          "required": [
            "LogicalOp"
          ],
          "additionalProperties": false
        },
        {
          "type": "object",
          "properties": {
            "AgentOp": {
              "$ref": "#/$defs/AgentOperation"
            }
          },
          "required": [
            "AgentOp"
          ],
          "additionalProperties": false
        }
      ]
    },
    "AtomicBinOp": {
      "type": "string",
      "enum": [
        "Add",
        "Sub",
        "Mul",
        "Div",
        "Pow",
        "Mod"
      ]
    },
    "AtomicUnaryOp": {
      "type": "string",
      "enum": [
        "Neg"
      ]
    },
    "ControlFlow": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "Start",
            "End",
            "If"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Loop": {
              "$ref": "#/$defs/LoopNodes"
            }
          },
          "required": [
            "Loop"
          ],
          "additionalProperties": false
        }
      ]
    },
    "LoopNodes": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "Start"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Continue": {
              "type": "string",
              "format": "uuid"
            }
          },
          "required": [
            "Continue"
          ],
          "additionalProperties": false
        }
      ]
    },
    "Variable": {
      "type": "string",
      "enum": [
        "Set",
        "Get"
      ]
    },
    "AtomicIo": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "ConsoleInput",
            "Read",
            "Write",
            "GetLine"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Open": {
              "$ref": "#/$defs/IoType"
            }
          },
          "required": [
            "Open"
          ],
          "additionalProperties": false
        }
      ]
    },
    "IoType": {
      "type": "string",
      "enum": [
        "File",
        "TcpSocket"
      ]
    },
    "AtomicLogic": {
      "type": "string",
      "enum": [
        "And",
        "Or",
        "Xor",
        "Not",
        "Eq"
      ]
    },
    "AgentOperation": {
      "oneOf": [
        {
          "type": "string",
          "enum": [
            "Send",
            "Recieve"
          ]
        },
        {
          "type": "object",
          "properties": {
            "Create": {
              "$ref": "#/$defs/AgentType"
            }
          },
          "required": [
            "Create"
          ],
          "additionalProperties": false
        }
      ]
    }
  }
}

=== mzearing/AgentNodes/agentnodes-editor/node-definitions/complex/group-1760638501429/node-1773944807413/compiled.json
{
  "inputs": [
    "Integer"
  ],
  "outputs": [],
  "defaults": {},
  "instances": {
    "6ba02bc9-6ac2-479b-8435-f65249bbcbb0": {
      "node_type": {
        "Atomic": {
          "Control": "Start"
        }
      },
      "default_overrides": {},
      "outputs": [],
      "control_flow_in": [],
      "control_flow_out": [
        [
          [
            "484c73c3-1d26-43df-af65-b80ffda3f269",
            0
          ]
        ]
      ],
      "inputs": []
    },
    "11594ca7-9274-4c5e-b242-a6942ca0d3bb": {
      "node_type": {
        "Atomic": "Print"
      },
      "default_overrides": {},
      "outputs": [],
      "control_flow_in": [
        [
          [
            "484c73c3-1d26-43df-af65-b80ffda3f269",
            0
          ]
        ]
      ],
      "control_flow_out": [
        []
      ],
      "inputs": [
        [
          "String",
          "484c73c3-1d26-43df-af65-b80ffda3f269",
          0
        ]
      ]
    },
    "484c73c3-1d26-43df-af65-b80ffda3f269": {
      "node_type": {
        "Atomic": {
          "Value": "Hello"
        }
      },
      "default_overrides": {},
      "outputs": [
        "11594ca7-9274-4c5e-b242-a6942ca0d3bb"
      ],
      "control_flow_in": [
        [
          [
            "6ba02bc9-6ac2-479b-8435-f65249bbcbb0",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "11594ca7-9274-4c5e-b242-a6942ca0d3bb",
            0
          ]
        ]
      ],
      "inputs": []
    }
  },
  "end_node": "11594ca7-9274-4c5e-b242-a6942ca0d3bb"
}

=== mzearing/AgentNodes/agentnodes-editor/node-definitions/complex/group-test-programs/even-or-odd/compiled.json
{
  "inputs": [
    "Integer"
  ],
  "outputs": [],
  "defaults": {},
  "instances": {
    "23e9a707-a144-4c09-865c-fa31a268853f": {
      "node_type": {
        "Atomic": {
          "Control": "Start"
        }
      },
      "default_overrides": {},
      "outputs": [
        "9b676e5a-186c-4a40-8066-397c1a212084"
      ],
      "control_flow_in": [],
      "control_flow_out": [
        [
          [
            "de3a000f-6462-417c-b9cd-faba4ebb9e0a",
            0
          ]
        ]
      ],
      "inputs": []
    },
    "9b676e5a-186c-4a40-8066-397c1a212084": {
      "node_type": {
        "Atomic": {
          "BinOp": "Mod"
        }
      },
      "default_overrides": {},
      "outputs": [
        "70756ca3-04f0-45b7-9196-34784fbc8f10"
      ],
      "control_flow_in": [
        [
          [
            "de3a000f-6462-417c-b9cd-faba4ebb9e0a",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "966d709f-39bf-4913-b2c5-875776f4fdc7",
            0
          ]
        ]
      ],
      "inputs": [
        [
          "Integer",
          "23e9a707-a144-4c09-865c-fa31a268853f",
          0
        ],
        [
          "Integer",
          "de3a000f-6462-417c-b9cd-faba4ebb9e0a",
          0
        ]
      ]
    },
    "966d709f-39bf-4913-b2c5-875776f4fdc7": {
      "node_type": {
        "Atomic": {
          "Value": 0
        }
      },
      "default_overrides": {},
      "outputs": [
        "70756ca3-04f0-45b7-9196-34784fbc8f10"
      ],
      "control_flow_in": [
        [
          [
            "9b676e5a-186c-4a40-8066-397c1a212084",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "70756ca3-04f0-45b7-9196-34784fbc8f10",
            0
          ]
        ]
      ],
      "inputs": []
    },
    "70756ca3-04f0-45b7-9196-34784fbc8f10": {
      "node_type": {
        "Atomic": {
          "LogicalOp": "Eq"
        }
      },
      "default_overrides": {},
      "outputs": [
        "bd6f5bcc-a8b2-4d08-bf39-d0895e0cbc71"
      ],
      "control_flow_in": [
        [
          [
            "966d709f-39bf-4913-b2c5-875776f4fdc7",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "bd6f5bcc-a8b2-4d08-bf39-d0895e0cbc71",
            0
          ]
        ]
      ],
      "inputs": [
        [
          "Integer",
          "9b676e5a-186c-4a40-8066-397c1a212084",
          0
        ],
        [
          "Integer",
          "966d709f-39bf-4913-b2c5-875776f4fdc7",
          0
        ]
      ]
    },
    "bd6f5bcc-a8b2-4d08-bf39-d0895e0cbc71": {
      "node_type": {
        "Atomic": {
          "Control": "If"
        }
      },
      "default_overrides": {},
      "outputs": [],
      "control_flow_in": [
        [
          [
            "70756ca3-04f0-45b7-9196-34784fbc8f10",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "010a547d-7d3f-4555-bcaf-1f19a71f420c",
            0
          ]
        ],
        [
          [
            "3f1079ed-752c-4fb0-b747-32745d04aa42",
            0
          ]
        ]
      ],
      "inputs": [
        [
          "Boolean",
          "70756ca3-04f0-45b7-9196-34784fbc8f10",
          0
        ]
      ]
    },
    "3f1079ed-752c-4fb0-b747-32745d04aa42": {
      "node_type": {
        "Atomic": {
          "Value": "Even"
        }
      },
      "default_overrides": {},
      "outputs": [
        "5ed72390-c9b8-4c0d-a761-e27e9deec90c"
      ],
      "control_flow_in": [
        [
          [
            "bd6f5bcc-a8b2-4d08-bf39-d0895e0cbc71",
            1
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "5ed72390-c9b8-4c0d-a761-e27e9deec90c",
            0
          ]
        ]
      ],
      "inputs": []
    },
    "5ed72390-c9b8-4c0d-a761-e27e9deec90c": {
      "node_type": {
        "Atomic": "Print"
      },
      "default_overrides": {},
      "outputs": [],
      "control_flow_in": [
        [
          [
            "3f1079ed-752c-4fb0-b747-32745d04aa42",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "5dd520c4-2fe5-4641-b5ba-2cdd9ec85612",
            0
          ]
        ]
      ],
      "inputs": [
        [
          "String",
          "3f1079ed-752c-4fb0-b747-32745d04aa42",
          0
        ]
      ]
    },
    "010a547d-7d3f-4555-bcaf-1f19a71f420c": {
      "node_type": {
        "Atomic": {
          "Value": "Odd"
        }
      },
      "default_overrides": {},
      "outputs": [
        "4677c815-150e-47c7-abed-054351d26f9b"
      ],
      "control_flow_in": [
        [
          [
            "bd6f5bcc-a8b2-4d08-bf39-d0895e0cbc71",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "4677c815-150e-47c7-abed-054351d26f9b",
            0
          ]
        ]
      ],
      "inputs": []
    },
    "4677c815-150e-47c7-abed-054351d26f9b": {
      "node_type": {
        "Atomic": "Print"
      },
      "default_overrides": {},
      "outputs": [],
      "control_flow_in": [
        [
          [
            "010a547d-7d3f-4555-bcaf-1f19a71f420c",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "5dd520c4-2fe5-4641-b5ba-2cdd9ec85612",
            0
          ]
        ]
      ],
      "inputs": [
        [
          "String",
          "010a547d-7d3f-4555-bcaf-1f19a71f420c",
          0
        ]
      ]
    },
    "5dd520c4-2fe5-4641-b5ba-2cdd9ec85612": {
      "node_type": {
        "Atomic": {
          "Control": "End"
        }
      },
      "default_overrides": {},
      "outputs": [],
      "control_flow_in": [
        [
          [
            "5ed72390-c9b8-4c0d-a761-e27e9deec90c",
            0
          ],
          [
            "4677c815-150e-47c7-abed-054351d26f9b",
            0
          ]
        ]
      ],
      "control_flow_out": [],
      "inputs": []
    },
    "de3a000f-6462-417c-b9cd-faba4ebb9e0a": {
      "node_type": {
        "Atomic": {
          "Value": 2
        }
      },
      "default_overrides": {},
      "outputs": [
        "9b676e5a-186c-4a40-8066-397c1a212084"
      ],
      "control_flow_in": [
        [
          [
            "23e9a707-a144-4c09-865c-fa31a268853f",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "9b676e5a-186c-4a40-8066-397c1a212084",
            0
          ]
        ]
      ],
      "inputs": []
    }
  },
  "end_node": "5dd520c4-2fe5-4641-b5ba-2cdd9ec85612"
}

=== mzearing/AgentNodes/agentnodes-editor/node-definitions/complex/group-test-programs/hello-world/compiled.json
{
  "inputs": [],
  "outputs": [],
  "defaults": {},
  "instances": {
    "8154b9b8-337b-4985-9049-71e49bf636db": {
      "node_type": {
        "Atomic": {
          "Control": "Start"
        }
      },
      "default_overrides": {},
      "outputs": [],
      "control_flow_in": [],
      "control_flow_out": [
        [
          [
            "7bafb742-fbf2-42b5-96d4-25adba977b47",
            0
          ]
        ]
      ],
      "inputs": []
    },
    "7bafb742-fbf2-42b5-96d4-25adba977b47": {
      "node_type": {
        "Atomic": {
          "Value": "Hello World"
        }
      },
      "default_overrides": {},
      "outputs": [
        "8510efc3-4aa2-427f-8c22-9141d8f733ab"
      ],
      "control_flow_in": [
        [
          [
            "8154b9b8-337b-4985-9049-71e49bf636db",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "8510efc3-4aa2-427f-8c22-9141d8f733ab",
            0
          ]
        ]
      ],
      "inputs": []
    },
    "8510efc3-4aa2-427f-8c22-9141d8f733ab": {
      "node_type": {
        "Atomic": "Print"
      },
      "default_overrides": {},
      "outputs": [],
      "control_flow_in": [
        [
          [
            "7bafb742-fbf2-42b5-96d4-25adba977b47",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "b4432ded-7595-4539-88ce-95a85806439a",
            0
          ]
        ]
      ],
      "inputs": [
        [
          "String",
          "7bafb742-fbf2-42b5-96d4-25adba977b47",
          0
        ]
      ]
    },
    "b4432ded-7595-4539-88ce-95a85806439a": {
      "node_type": {
        "Atomic": {
          "Control": "End"
        }
      },
      "default_overrides": {},
      "outputs": [],
      "control_flow_in": [
        [
          [
            "8510efc3-4aa2-427f-8c22-9141d8f733ab",
            0
          ]
        ]
      ],
      "control_flow_out": [],
      "inputs": []
    }
  },
  "end_node": "b4432ded-7595-4539-88ce-95a85806439a"
}

=== mzearing/AgentNodes/agentnodes-editor/node-definitions/complex/group-test-programs/string-concat/compiled.json
{
  "inputs": [],
  "outputs": [
    "String"
  ],
  "defaults": {},
  "instances": {
    "28ba2db6-91b9-4419-93f1-5212e8ac8a0e": {
      "node_type": {
        "Atomic": {
          "Control": "Start"
        }
      },
      "default_overrides": {},
      "outputs": [],
      "control_flow_in": [],
      "control_flow_out": [
        [
          [
            "1dd3c0bf-d123-494f-998d-c224dae1bce2",
            0
          ]
        ]
      ],
      "inputs": []
    },
    "baf01ad3-09ba-409d-be7b-fa2fffa309f8": {
      "node_type": {
        "Atomic": {
          "BinOp": "Add"
        }
      },
      "default_overrides": {},
      "outputs": [
        "88dcb5fb-2fd1-4046-a2df-fa671af9c61f"
      ],
      "control_flow_in": [
        [
          [
            "79686ac2-0940-4e8d-82e0-2f40b42e4877",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "88dcb5fb-2fd1-4046-a2df-fa671af9c61f",
            0
          ]
        ]
      ],
      "inputs": [
        [
          "String",
          "1dd3c0bf-d123-494f-998d-c224dae1bce2",
          0
        ],
        [
          "String",
          "79686ac2-0940-4e8d-82e0-2f40b42e4877",
          0
        ]
      ]
    },
    "88dcb5fb-2fd1-4046-a2df-fa671af9c61f": {
      "node_type": {
        "Atomic": {
          "Control": "End"
        }
      },
      "default_overrides": {},
      "outputs": [
        "41bc73fd-3f0e-4075-892f-3a3dc215f4b0"
      ],
      "control_flow_in": [
        [
          [
            "baf01ad3-09ba-409d-be7b-fa2fffa309f8",
            0
          ]
        ]
      ],
      "control_flow_out": [],
      "inputs": [
        [
          "String",
          "baf01ad3-09ba-409d-be7b-fa2fffa309f8",
          0
        ]
      ]
    },
    "1dd3c0bf-d123-494f-998d-c224dae1bce2": {
      "node_type": {
        "Atomic": {
          "Value": "Hello "
        }
      },
      "default_overrides": {},
      "outputs": [
        "baf01ad3-09ba-409d-be7b-fa2fffa309f8"
      ],
      "control_flow_in": [
        [
          [
            "28ba2db6-91b9-4419-93f1-5212e8ac8a0e",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "79686ac2-0940-4e8d-82e0-2f40b42e4877",
            0
          ]
        ]
      ],
      "inputs": []
    },
    "79686ac2-0940-4e8d-82e0-2f40b42e4877": {
      "node_type": {
        "Atomic": {
          "Value": "World"
        }
      },
      "default_overrides": {},
      "outputs": [
        "baf01ad3-09ba-409d-be7b-fa2fffa309f8"
      ],
      "control_flow_in": [
        [
          [
            "1dd3c0bf-d123-494f-998d-c224dae1bce2",
            0
          ]
        ]
      ],
      "control_flow_out": [
        [
          [
            "baf01ad3-09ba-409d-be7b-fa2fffa309f8",
            0
          ]
        ]
      ],
      "inputs": []
    }
  },
  "end_node": "88dcb5fb-2fd1-4046-a2df-fa671af9c61f"
}
